### ISSUE TITLE
:sparkles: Velocity Calculation Improvement

### ISSUE THREAD

**Issue by SizzinSeal** [Jerrylum/path.jerryio#20]
**Is your feature request related to a problem? Please describe.**
Bent Rate Application Range can be confusing to tune, and bent rate is not an accurate representation of how the robot should slow down around curves.

**Describe the solution you'd like**
Radius should be used to calculate the speed at each point. This method is more accurate and easier to tune

Radius at any point can be calculated by this formula:
![radius_function](https://github.com/Jerrylum/path.jerryio/assets/111480281/1a670ed1-ace6-4ad3-8917-a43706a78edd)

Maximum speed due to curvature can be calculated with this formula:
![speed_equation](https://github.com/Jerrylum/path.jerryio/assets/111480281/5b1fca0d-a701-4d1d-bff8-9aba109c4d34)

where `v` is the maximum speed,  `r` is the radius and `u` is the coefficient of friction. `u` is the value that should be tuned by the user. It is the coefficent of friction.

**Comment by Jerrylum** [comment]
This is now solved in 0.6.0 by using curvature as the bent rate. More information can be found in the documentation: https://docs.path.jerryio.com/docs/user-guides/concepts#bent-rate-and-speed-calculation
