### ISSUE TITLE
:bug: Poor Performance on Firefox

### ISSUE THREAD

**Issue by SizzinSeal** [Jerrylum/path.jerryio#38]
**Describe the bug**
If you are hovering your mouse over the field, the coordinates in the bottom right only update once approximately 2 seconds. If you hold left click however, its fast. Zooming in/out of the field and panning the field is also very laggy

**To Reproduce**
1. Open https://path.jerryio.com/ on firefox
2. move your mouse over the field
3. observe slow update of coordinates on the bottom right

**Expected behavior**
For the coordinates to update really quickly

**Desktop (please complete the following information):**
 - OS: Windows 11, CachyOS linux 6.9.5 (using wayland, x11 untested)
 - Browser: Firefox v127.0.1
 - Version: 0.7.0

**Comment by Jerrylum** [comment]
Do you wnat to try it again in version 0.8.0?

**Comment by SizzinSeal** [comment]
So I found the cause of this problem. It was a bad extension (canvas blocker). Removing it fixed everything
