### ISSUE TITLE
:bug: Small logic error

### ISSUE THREAD

**Issue by wjaaaaaaat** [Jerrylum/path.jerryio#47]
**Describe the bug**
Line 518 in src/core/Command.ts is wrong.
https://github.com/Jerrylum/path.jerryio/blob/a4d69f69feda9065cd75ac88463371144463224d/src/core/Command.ts#L518
It should be:
`this.variant = segment.isCubic() ? SegmentVariant.Cubic : SegmentVariant.Linear;`
I don't know what this affects, if anything; I only saw it in the code.
This error was created in the resolution of issue #23 Q3.

**Comment by Jerrylum** [comment]
After I reviewed the code, I believe the purpose of the property `this.variant` is to store the target variant after executing the `ConvertSegment` command. Therefore, it shouldn't be a logical bug. However, it should be renamed to `this.targetVariant` or something else to better declare its intended purpose.
