### ISSUE TITLE
:sparkles: Mouse Field Coordinates

### ISSUE THREAD

**Issue by SizzinSeal** [Jerrylum/path.jerryio#8]
**Describe the solution you'd like**
The coordinates of the mouse on the field should be displayed. This will make creating autos with non-path-following algorithms easier.

**Additional context**
I've had multiple LemLib users ask for this feature. Its annoying to have both this path generator and the lemlib path generator open at the same time just to use the mouse coordinates feature in the lemlib path generator.

**Comment by Jerrylum** [comment]
Added in 0.4.0
